version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go
    commit-message:
      prefix: "chore(deps)"
      include: scope
    groups:
      aws-sdk:
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"
      otel:
        patterns:
          - "go.opentelemetry.io/*"
      cobra-viper:
        patterns:
          - "github.com/spf13/cobra"
          - "github.com/spf13/viper"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "chore(ci)"
