package cmd

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

func initCmd() *cobra.Command {
	var force bool
	c := &cobra.Command{
		Use:   "init",
		Short: "Wizard interactif pour générer un fichier de configuration .osc-policy.yaml",
		Long: `Génère un fichier .osc-policy.yaml dans le répertoire courant en posant
quelques questions sur le profil souhaité, la sévérité minimale, les
frameworks de conformité ciblés et les règles à exclure.

Le fichier généré peut être versionné en Git pour partager la configuration
avec l'équipe.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			path := ".osc-policy.yaml"
			if _, err := os.Stat(path); err == nil && !force {
				return fmt.Errorf("%s existe déjà — utiliser --force pour écraser", path)
			}

			r := bufio.NewReader(os.Stdin)
			fmt.Println()
			fmt.Println("─── Wizard osc-policy init ─────────────────────────────────────────")
			fmt.Println()

			profile := ask(r, "Profile (security|finops|compliance|all)", "all")
			severity := ask(r, "Sévérité minimale à reporter (LOW|MEDIUM|HIGH|CRITICAL)", "LOW")
			failOn := ask(r, "Sévérité qui fait échouer le scan en CI (LOW|MEDIUM|HIGH|CRITICAL)", "HIGH")
			minGrade := ask(r, "Grade minimum requis (A|B|C|D|E|F|G, vide = pas de seuil)", "")
			region := ask(r, "Région Outscale par défaut", "eu-west-2")
			framework := ask(r, "Framework de conformité prioritaire (vide = tous, ex: SECNUMCLOUD-3.2)", "")

			content := generateConfig(profile, severity, failOn, minGrade, region, framework)
			if err := os.WriteFile(path, []byte(content), 0644); err != nil {
				return fmt.Errorf("écriture %s: %w", path, err)
			}

			fmt.Println()
			fmt.Printf("✓ %s créé. Vous pouvez maintenant lancer :\n", path)
			fmt.Println("    osc-policy scan live")
			fmt.Println("    osc-policy scan plan plan.json")
			fmt.Println()
			return nil
		},
	}
	c.Flags().BoolVar(&force, "force", false, "Écraser le fichier existant")
	return c
}

func ask(r *bufio.Reader, question, defaultVal string) string {
	if defaultVal != "" {
		fmt.Printf("  %s [%s] : ", question, defaultVal)
	} else {
		fmt.Printf("  %s : ", question)
	}
	line, _ := r.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return defaultVal
	}
	return line
}

func generateConfig(profile, severity, failOn, minGrade, region, framework string) string {
	var sb strings.Builder
	sb.WriteString("# osc-policy configuration\n")
	sb.WriteString("# Generated by `osc-policy init`. Versionner ce fichier en Git.\n\n")

	sb.WriteString("scan:\n")
	sb.WriteString(fmt.Sprintf("  profile: %s\n", profile))
	sb.WriteString(fmt.Sprintf("  severity: %s\n", severity))
	sb.WriteString(fmt.Sprintf("  fail_on: %s\n", failOn))
	if minGrade != "" {
		sb.WriteString(fmt.Sprintf("  min_grade: %s\n", minGrade))
	}
	if framework != "" {
		sb.WriteString(fmt.Sprintf("  framework: %s\n", framework))
	}
	sb.WriteString("  # Liste de règles à ignorer (avec justification).\n")
	sb.WriteString("  # skip_rules:\n")
	sb.WriteString("  #   - OSC-XXX-NNN  # raison: ...\n\n")

	sb.WriteString("outscale:\n")
	sb.WriteString(fmt.Sprintf("  region: %s\n", region))
	sb.WriteString("  # profile: default  # profil ~/.osc/config.json\n\n")

	sb.WriteString("policies:\n")
	sb.WriteString("  # extra_dir: ./custom-policies  # policies Rego custom\n\n")

	sb.WriteString("finops:\n")
	sb.WriteString("  # prices_file: ./catalog/prices.yaml  # override du catalogue tarifaire\n")
	return sb.String()
}
