name: osv-scanner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '23 4 * * 1'

concurrency:
  group: osv-scanner-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  scan:
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@9a498708959aeaef5ef730655706c5a1df1edbc2 # v2.3.8
    with:
      scan-args: |-
        --recursive
        --skip-git
        ./
    permissions:
      contents: read
      security-events: write
      actions: read
