name: osv-scanner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '23 4 * * 1'

concurrency:
  group: osv-scanner-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  scan:
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@e69cc6c86b31f1e7e23935bbe7031b50e51082de # v2.0.2
    with:
      scan-args: |-
        --recursive
        --skip-git
        ./
    permissions:
      contents: read
      security-events: write
      actions: read
